const nbaLogoSlugMap = { NOP: 'no', NYK: 'ny', SAS: 'sa', UTA: 'utah', WAS: 'wsh' };

const nbaLogo = (abbr) => `https://a.espncdn.com/i/teamlogos/nba/500/${(nbaLogoSlugMap[abbr] ?? abbr).toLowerCase()}.png`;
const nflLogo = (abbr) => `https://a.espncdn.com/i/teamlogos/nfl/500/${abbr.toLowerCase()}.png`;
const kboLogoCodeMap = { DSB: 'OB', HAN: 'HH', KIA: 'HT', KIW: 'WO', KTW: 'KT', LGT: 'LG', LOT: 'LT', NCD: 'NC', SAM: 'SS', SSG: 'SK' };
const kboLogo = (abbr) => `https://6ptotvmi5753.edge.naverncp.com/KBO_IMAGE/KBOHome/resources/images/emblem/regular/2026/emblem_${kboLogoCodeMap[abbr] ?? abbr}.png`;
const team = (entry) => ({ ...entry, key: `${entry.league}:${entry.abbr}` });

export const allTeams = [
  team({ abbr: 'ATL', name: 'Atlanta Hawks', league: 'NBA', colors: ['#C8102E', '#FDB927'], mark: 'A', newsQuery: 'Atlanta Hawks NBA', logo: nbaLogo('ATL') }),
  team({ abbr: 'BOS', name: 'Boston Celtics', league: 'NBA', colors: ['#007A33', '#BA9653'], mark: '☘', newsQuery: 'Boston Celtics NBA', logo: nbaLogo('BOS') }),
  team({ abbr: 'BKN', name: 'Brooklyn Nets', league: 'NBA', colors: ['#111111', '#FFFFFF'], mark: 'B', newsQuery: 'Brooklyn Nets NBA', logo: nbaLogo('BKN') }),
  team({ abbr: 'CHA', name: 'Charlotte Hornets', league: 'NBA', colors: ['#1D1160', '#00788C'], mark: 'C', newsQuery: 'Charlotte Hornets NBA', logo: nbaLogo('CHA') }),
  team({ abbr: 'CHI', name: 'Chicago Bulls', league: 'NBA', colors: ['#CE1141', '#111111'], mark: 'C', newsQuery: 'Chicago Bulls NBA', logo: nbaLogo('CHI') }),
  team({ abbr: 'CLE', name: 'Cleveland Cavaliers', league: 'NBA', colors: ['#6F263D', '#FFB81C'], mark: 'C', newsQuery: 'Cleveland Cavaliers NBA', logo: nbaLogo('CLE') }),
  team({ abbr: 'DAL', name: 'Dallas Mavericks', league: 'NBA', colors: ['#00538C', '#B8C4CA'], mark: 'D', newsQuery: 'Dallas Mavericks NBA', logo: nbaLogo('DAL') }),
  team({ abbr: 'DEN', name: 'Denver Nuggets', league: 'NBA', colors: ['#0E2240', '#FEC524'], mark: 'D', newsQuery: 'Denver Nuggets NBA', logo: nbaLogo('DEN') }),
  team({ abbr: 'DET', name: 'Detroit Pistons', league: 'NBA', colors: ['#C8102E', '#1D42BA'], mark: 'D', newsQuery: 'Detroit Pistons NBA', logo: nbaLogo('DET') }),
  team({ abbr: 'GSW', name: 'Golden State Warriors', league: 'NBA', colors: ['#1D428A', '#FFC72C'], mark: 'G', newsQuery: 'Golden State Warriors NBA', logo: nbaLogo('GSW') }),
  team({ abbr: 'HOU', name: 'Houston Rockets', league: 'NBA', colors: ['#CE1141', '#111111'], mark: 'H', newsQuery: 'Houston Rockets NBA', logo: nbaLogo('HOU') }),
  team({ abbr: 'IND', name: 'Indiana Pacers', league: 'NBA', colors: ['#002D62', '#FDBB30'], mark: 'I', newsQuery: 'Indiana Pacers NBA', logo: nbaLogo('IND') }),
  team({ abbr: 'LAC', name: 'LA Clippers', league: 'NBA', colors: ['#C8102E', '#1D428A'], mark: 'C', newsQuery: 'LA Clippers NBA', logo: nbaLogo('LAC') }),
  team({ abbr: 'LAL', name: 'Los Angeles Lakers', league: 'NBA', colors: ['#552583', '#FDB927'], mark: 'L', newsQuery: 'Los Angeles Lakers NBA', logo: nbaLogo('LAL') }),
  team({ abbr: 'MEM', name: 'Memphis Grizzlies', league: 'NBA', colors: ['#5D76A9', '#12173F'], mark: 'M', newsQuery: 'Memphis Grizzlies NBA', logo: nbaLogo('MEM') }),
  team({ abbr: 'MIA', name: 'Miami Heat', league: 'NBA', colors: ['#98002E', '#F9A01B'], mark: 'H', newsQuery: 'Miami Heat NBA', logo: nbaLogo('MIA') }),
  team({ abbr: 'MIL', name: 'Milwaukee Bucks', league: 'NBA', colors: ['#00471B', '#EEE1C6'], mark: 'M', newsQuery: 'Milwaukee Bucks NBA', logo: nbaLogo('MIL') }),
  team({ abbr: 'MIN', name: 'Minnesota Timberwolves', league: 'NBA', colors: ['#0C2340', '#236192'], mark: 'M', newsQuery: 'Minnesota Timberwolves NBA', logo: nbaLogo('MIN') }),
  team({ abbr: 'NOP', name: 'New Orleans Pelicans', league: 'NBA', colors: ['#0C2340', '#C8102E'], mark: 'N', newsQuery: 'New Orleans Pelicans NBA', logo: nbaLogo('NOP') }),
  team({ abbr: 'NYK', name: 'New York Knicks', league: 'NBA', colors: ['#006BB6', '#F58426'], mark: 'K', newsQuery: 'New York Knicks NBA', logo: nbaLogo('NYK') }),
  team({ abbr: 'OKC', name: 'Oklahoma City Thunder', league: 'NBA', colors: ['#007AC1', '#EF3B24'], mark: 'O', newsQuery: 'Oklahoma City Thunder NBA', logo: nbaLogo('OKC') }),
  team({ abbr: 'ORL', name: 'Orlando Magic', league: 'NBA', colors: ['#0077C0', '#C4CED4'], mark: 'O', newsQuery: 'Orlando Magic NBA', logo: nbaLogo('ORL') }),
  team({ abbr: 'PHI', name: 'Philadelphia 76ers', league: 'NBA', colors: ['#006BB6', '#ED174C'], mark: 'P', newsQuery: 'Philadelphia 76ers NBA', logo: nbaLogo('PHI') }),
  team({ abbr: 'PHX', name: 'Phoenix Suns', league: 'NBA', colors: ['#1D1160', '#E56020'], mark: 'S', newsQuery: 'Phoenix Suns NBA', logo: nbaLogo('PHX') }),
  team({ abbr: 'POR', name: 'Portland Trail Blazers', league: 'NBA', colors: ['#E03A3E', '#111111'], mark: 'P', newsQuery: 'Portland Trail Blazers NBA', logo: nbaLogo('POR') }),
  team({ abbr: 'SAC', name: 'Sacramento Kings', league: 'NBA', colors: ['#5A2D81', '#63727A'], mark: 'S', newsQuery: 'Sacramento Kings NBA', logo: nbaLogo('SAC') }),
  team({ abbr: 'SAS', name: 'San Antonio Spurs', league: 'NBA', colors: ['#111111', '#C4CED4'], mark: 'S', newsQuery: 'San Antonio Spurs NBA', logo: nbaLogo('SAS') }),
  team({ abbr: 'TOR', name: 'Toronto Raptors', league: 'NBA', colors: ['#CE1141', '#111111'], mark: 'T', newsQuery: 'Toronto Raptors NBA', logo: nbaLogo('TOR') }),
  team({ abbr: 'UTA', name: 'Utah Jazz', league: 'NBA', colors: ['#002B5C', '#F9A01B'], mark: 'U', newsQuery: 'Utah Jazz NBA', logo: nbaLogo('UTA') }),
  team({ abbr: 'WAS', name: 'Washington Wizards', league: 'NBA', colors: ['#002B5C', '#E31837'], mark: 'W', newsQuery: 'Washington Wizards NBA', logo: nbaLogo('WAS') }),
  team({ abbr: 'ARI', name: 'Arizona Cardinals', league: 'NFL', colors: ['#97233F', '#000000'], mark: 'A', newsQuery: 'Arizona Cardinals NFL', logo: nflLogo('ARI') }),
  team({ abbr: 'ATL', name: 'Atlanta Falcons', league: 'NFL', colors: ['#A71930', '#000000'], mark: 'F', newsQuery: 'Atlanta Falcons NFL', logo: nflLogo('ATL') }),
  team({ abbr: 'BAL', name: 'Baltimore Ravens', league: 'NFL', colors: ['#241773', '#000000'], mark: 'R', newsQuery: 'Baltimore Ravens NFL', logo: nflLogo('BAL') }),
  team({ abbr: 'BUF', name: 'Buffalo Bills', league: 'NFL', colors: ['#00338D', '#C60C30'], mark: 'B', newsQuery: 'Buffalo Bills NFL', logo: nflLogo('BUF') }),
  team({ abbr: 'CAR', name: 'Carolina Panthers', league: 'NFL', colors: ['#0085CA', '#101820'], mark: 'C', newsQuery: 'Carolina Panthers NFL', logo: nflLogo('CAR') }),
  team({ abbr: 'CHI', name: 'Chicago Bears', league: 'NFL', colors: ['#0B162A', '#C83803'], mark: 'B', newsQuery: 'Chicago Bears NFL', logo: nflLogo('CHI') }),
  team({ abbr: 'CIN', name: 'Cincinnati Bengals', league: 'NFL', colors: ['#FB4F14', '#111111'], mark: 'B', newsQuery: 'Cincinnati Bengals NFL', logo: nflLogo('CIN') }),
  team({ abbr: 'CLE', name: 'Cleveland Browns', league: 'NFL', colors: ['#311D00', '#FF3C00'], mark: 'B', newsQuery: 'Cleveland Browns NFL', logo: nflLogo('CLE') }),
  team({ abbr: 'DAL', name: 'Dallas Cowboys', league: 'NFL', colors: ['#041E42', '#869397'], mark: 'D', newsQuery: 'Dallas Cowboys NFL', logo: nflLogo('DAL') }),
  team({ abbr: 'DEN', name: 'Denver Broncos', league: 'NFL', colors: ['#FB4F14', '#002244'], mark: 'D', newsQuery: 'Denver Broncos NFL', logo: nflLogo('DEN') }),
  team({ abbr: 'DET', name: 'Detroit Lions', league: 'NFL', colors: ['#0076B6', '#B0B7BC'], mark: 'L', newsQuery: 'Detroit Lions NFL', logo: nflLogo('DET') }),
  team({ abbr: 'GB', name: 'Green Bay Packers', league: 'NFL', colors: ['#203731', '#FFB612'], mark: 'G', newsQuery: 'Green Bay Packers NFL', logo: nflLogo('GB') }),
  team({ abbr: 'HOU', name: 'Houston Texans', league: 'NFL', colors: ['#03202F', '#A71930'], mark: 'H', newsQuery: 'Houston Texans NFL', logo: nflLogo('HOU') }),
  team({ abbr: 'IND', name: 'Indianapolis Colts', league: 'NFL', colors: ['#002C5F', '#A2AAAD'], mark: 'I', newsQuery: 'Indianapolis Colts NFL', logo: nflLogo('IND') }),
  team({ abbr: 'JAX', name: 'Jacksonville Jaguars', league: 'NFL', colors: ['#006778', '#9F792C'], mark: 'J', newsQuery: 'Jacksonville Jaguars NFL', logo: nflLogo('JAX') }),
  team({ abbr: 'KC', name: 'Kansas City Chiefs', league: 'NFL', colors: ['#E31837', '#FFB81C'], mark: 'KC', newsQuery: 'Kansas City Chiefs NFL', logo: nflLogo('KC') }),
  team({ abbr: 'LAC', name: 'Los Angeles Chargers', league: 'NFL', colors: ['#0080C6', '#FFC20E'], mark: 'C', newsQuery: 'Los Angeles Chargers NFL', logo: nflLogo('LAC') }),
  team({ abbr: 'LAR', name: 'Los Angeles Rams', league: 'NFL', colors: ['#003594', '#FFA300'], mark: 'R', newsQuery: 'Los Angeles Rams NFL', logo: nflLogo('LAR') }),
  team({ abbr: 'LV', name: 'Las Vegas Raiders', league: 'NFL', colors: ['#000000', '#A5ACAF'], mark: 'R', newsQuery: 'Las Vegas Raiders NFL', logo: nflLogo('LV') }),
  team({ abbr: 'MIA', name: 'Miami Dolphins', league: 'NFL', colors: ['#008E97', '#FC4C02'], mark: 'M', newsQuery: 'Miami Dolphins NFL', logo: nflLogo('MIA') }),
  team({ abbr: 'MIN', name: 'Minnesota Vikings', league: 'NFL', colors: ['#4F2683', '#FFC62F'], mark: 'V', newsQuery: 'Minnesota Vikings NFL', logo: nflLogo('MIN') }),
  team({ abbr: 'NE', name: 'New England Patriots', league: 'NFL', colors: ['#002244', '#C60C30'], mark: 'P', newsQuery: 'New England Patriots NFL', logo: nflLogo('NE') }),
  team({ abbr: 'NO', name: 'New Orleans Saints', league: 'NFL', colors: ['#D3BC8D', '#101820'], mark: 'S', newsQuery: 'New Orleans Saints NFL', logo: nflLogo('NO') }),
  team({ abbr: 'NYG', name: 'New York Giants', league: 'NFL', colors: ['#0B2265', '#A71930'], mark: 'G', newsQuery: 'New York Giants NFL', logo: nflLogo('NYG') }),
  team({ abbr: 'NYJ', name: 'New York Jets', league: 'NFL', colors: ['#125740', '#FFFFFF'], mark: 'J', newsQuery: 'New York Jets NFL', logo: nflLogo('NYJ') }),
  team({ abbr: 'PHI', name: 'Philadelphia Eagles', league: 'NFL', colors: ['#004C54', '#A5ACAF'], mark: 'E', newsQuery: 'Philadelphia Eagles NFL', logo: nflLogo('PHI') }),
  team({ abbr: 'PIT', name: 'Pittsburgh Steelers', league: 'NFL', colors: ['#FFB612', '#101820'], mark: 'P', newsQuery: 'Pittsburgh Steelers NFL', logo: nflLogo('PIT') }),
  team({ abbr: 'SEA', name: 'Seattle Seahawks', league: 'NFL', colors: ['#002244', '#69BE28'], mark: 'S', newsQuery: 'Seattle Seahawks NFL', logo: nflLogo('SEA') }),
  team({ abbr: 'SF', name: 'San Francisco 49ers', league: 'NFL', colors: ['#AA0000', '#B3995D'], mark: 'SF', newsQuery: 'San Francisco 49ers NFL', logo: nflLogo('SF') }),
  team({ abbr: 'TB', name: 'Tampa Bay Buccaneers', league: 'NFL', colors: ['#D50A0A', '#34302B'], mark: 'T', newsQuery: 'Tampa Bay Buccaneers NFL', logo: nflLogo('TB') }),
  team({ abbr: 'TEN', name: 'Tennessee Titans', league: 'NFL', colors: ['#0C2340', '#4B92DB'], mark: 'T', newsQuery: 'Tennessee Titans NFL', logo: nflLogo('TEN') }),
  team({ abbr: 'WSH', name: 'Washington Commanders', league: 'NFL', colors: ['#5A1414', '#FFB612'], mark: 'W', newsQuery: 'Washington Commanders NFL', logo: nflLogo('WSH') }),
  team({ abbr: 'DSB', name: 'Doosan Bears', league: 'KBO', colors: ['#131230', '#ED1C24'], mark: 'DB', newsQuery: 'Doosan Bears KBO', logo: kboLogo('DSB') }),
  team({ abbr: 'HAN', name: 'Hanwha Eagles', league: 'KBO', colors: ['#FF6600', '#1E3765'], mark: 'HE', newsQuery: 'Hanwha Eagles KBO', logo: kboLogo('HAN') }),
  team({ abbr: 'KIA', name: 'KIA Tigers', league: 'KBO', colors: ['#EA0029', '#111111'], mark: 'K', newsQuery: 'KIA Tigers KBO', logo: kboLogo('KIA') }),
  team({ abbr: 'KIW', name: 'Kiwoom Heroes', league: 'KBO', colors: ['#5B0D1B', '#B79E6E'], mark: 'KH', newsQuery: 'Kiwoom Heroes KBO', logo: kboLogo('KIW') }),
  team({ abbr: 'KTW', name: 'KT Wiz', league: 'KBO', colors: ['#111111', '#ED1B2F'], mark: 'KT', newsQuery: 'KT Wiz KBO', logo: kboLogo('KTW') }),
  team({ abbr: 'LGT', name: 'LG Twins', league: 'KBO', colors: ['#A50034', '#C6C9CA'], mark: 'LG', newsQuery: 'LG Twins KBO', logo: kboLogo('LGT') }),
  team({ abbr: 'LOT', name: 'Lotte Giants', league: 'KBO', colors: ['#002955', '#E31B23'], mark: 'LT', newsQuery: 'Lotte Giants KBO', logo: kboLogo('LOT') }),
  team({ abbr: 'NCD', name: 'NC Dinos', league: 'KBO', colors: ['#1D467D', '#C2A25D'], mark: 'NC', newsQuery: 'NC Dinos KBO', logo: kboLogo('NCD') }),
  team({ abbr: 'SAM', name: 'Samsung Lions', league: 'KBO', colors: ['#074CA1', '#FFFFFF'], mark: 'SL', newsQuery: 'Samsung Lions KBO', logo: kboLogo('SAM') }),
  team({ abbr: 'SSG', name: 'SSG Landers', league: 'KBO', colors: ['#CE0E2D', '#FDB827'], mark: 'SSG', newsQuery: 'SSG Landers KBO', logo: kboLogo('SSG') }),
];

export const getLeagueTeams = (league) => allTeams.filter((entry) => league === 'ALL' || entry.league === league);
export const getTeamByKey = (key) => allTeams.find((entry) => entry.key === key);
export const getTeamByAbbr = (abbr, league) => allTeams.find((entry) => entry.abbr === abbr && (!league || entry.league === league));
