import type { Match } from './types';

function pad(value: number) {
  return String(value).padStart(2, '0');
}

function buildSeedSchedule(offsetDays: number, hour: number, minute: number) {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + offsetDays);
  date.setHours(hour, minute, 0, 0);

  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const startDate = `${year}-${month}-${day}T${pad(hour)}:${pad(minute)}:00+09:00`;

  let startTime = `${month}월 ${day}일 ${pad(hour)}:${pad(minute)}`;
  if (offsetDays === 0) startTime = `오늘 ${pad(hour)}:${pad(minute)}`;
  if (offsetDays === -1) startTime = `어제 ${pad(hour)}:${pad(minute)}`;
  if (offsetDays === 1) startTime = `내일 ${pad(hour)}:${pad(minute)}`;

  let dateBucket: Match['dateBucket'] = 'TODAY';
  if (offsetDays < 0) dateBucket = offsetDays === -1 ? 'YESTERDAY' : 'YESTERDAY';
  if (offsetDays > 0) dateBucket = 'UPCOMING';

  return { startDate, startTime, dateBucket };
}

export const initialMatches: Match[] = [
  {
    id: 1,
    league: 'NBA',
    status: 'LIVE',
    ...buildSeedSchedule(0, 20, 30),
    homeAbbr: 'LAL',
    awayAbbr: 'BOS',
    homeRecord: '49-27',
    awayRecord: '55-21',
    homeTeam: 'Lakers',
    awayTeam: 'Celtics',
    homeScore: 102,
    awayScore: 99,
    period: '4Q · 02:14',
    venue: 'Crypto.com Arena',
    headline: '접전 끝 승부처 돌입',
    summary: '레이커스가 4쿼터 막판 속공과 자유투로 3점 차 리드를 지키는 중입니다.',
    keyStats: [
      { label: '리바운드', value: '40 - 44', awayValue: 40, homeValue: 44 },
      { label: '3점 성공', value: '13 - 14', awayValue: 13, homeValue: 14 },
      { label: '턴오버', value: '11 - 9', awayValue: 11, homeValue: 9 },
      { label: '페인트 존 득점', value: '42 - 48', awayValue: 42, homeValue: 48 },
    ],
    playByPlay: ['2:14 레이커스 자유투 2개 성공', '3:02 테이텀 3점 성공', '4:15 르브론 속공 덩크'],
    lastUpdated: '방금 전',
  },
  {
    id: 2,
    league: 'NFL',
    status: 'LIVE',
    ...buildSeedSchedule(0, 21, 0),
    homeAbbr: 'KC',
    awayAbbr: 'BUF',
    homeRecord: '10-3',
    awayRecord: '9-4',
    homeTeam: 'Chiefs',
    awayTeam: 'Bills',
    homeScore: 24,
    awayScore: 21,
    period: '4Q · 08:41',
    venue: 'Arrowhead Stadium',
    headline: '터치다운 공방 계속',
    summary: '치프스가 레드존 효율에서 앞서며 빌스와 치열한 공방전을 이어가고 있습니다.',
    keyStats: [
      { label: '패싱 야드', value: '271 - 286', awayValue: 271, homeValue: 286 },
      { label: '러싱 야드', value: '88 - 97', awayValue: 88, homeValue: 97 },
      { label: '턴오버', value: '1 - 0', awayValue: 1, homeValue: 0 },
      { label: '3rd Down', value: '5/11 - 6/12' },
    ],
    playByPlay: ['08:41 치프스 필드골 성공', '10:12 빌스 터치다운 드라이브', '12:55 치프스 인터셉션 유도'],
    lastUpdated: '1분 전',
  },
  {
    id: 3,
    league: 'NBA',
    status: 'FINAL',
    ...buildSeedSchedule(0, 17, 0),
    homeAbbr: 'GSW',
    awayAbbr: 'PHX',
    homeRecord: '46-30',
    awayRecord: '43-33',
    homeTeam: 'Warriors',
    awayTeam: 'Suns',
    homeScore: 118,
    awayScore: 110,
    period: '경기 종료',
    venue: 'Chase Center',
    headline: '커리 34점 활약',
    summary: '워리어스가 3점슛 성공률 우위를 바탕으로 선즈를 제압했습니다.',
    keyStats: [
      { label: '3점 성공', value: '12 - 19', awayValue: 12, homeValue: 19 },
      { label: '어시스트', value: '24 - 31', awayValue: 24, homeValue: 31 },
      { label: '자유투', value: '18 - 15', awayValue: 18, homeValue: 15 },
    ],
    playByPlay: ['4Q 종료 워리어스 승리 확정', '1:22 커리 3점 성공', '2:01 듀란트 점퍼 성공'],
    lastUpdated: '14분 전',
  },
  {
    id: 4,
    league: 'NFL',
    status: 'UPCOMING',
    ...buildSeedSchedule(1, 9, 20),
    homeAbbr: 'SF',
    awayAbbr: 'PHI',
    homeRecord: '11-2',
    awayRecord: '10-3',
    homeTeam: '49ers',
    awayTeam: 'Eagles',
    homeScore: 0,
    awayScore: 0,
    period: '킥오프 대기',
    venue: 'Levi\'s Stadium',
    headline: '프라임 매치업 예정',
    summary: '양 팀 모두 강한 수비를 앞세워 중요한 맞대결을 준비하고 있습니다.',
    keyStats: [
      { label: '예상 관전 포인트', value: '수비 라인 대결' },
      { label: '주목 선수', value: 'Hurts / McCaffrey' },
      { label: '경기 중요도', value: '플레이오프 경쟁' },
    ],
    playByPlay: ['킥오프 전입니다.', '선발 라인업 대기 중입니다.'],
    lastUpdated: '일정 확정',
  },
  {
    id: 5,
    league: 'NBA',
    status: 'FINAL',
    ...buildSeedSchedule(-1, 19, 0),
    homeAbbr: 'NYK',
    awayAbbr: 'MIA',
    homeRecord: '45-31',
    awayRecord: '41-35',
    homeTeam: 'Knicks',
    awayTeam: 'Heat',
    homeScore: 109,
    awayScore: 101,
    period: '경기 종료',
    venue: 'Madison Square Garden',
    headline: '브런슨 29점으로 승부 마무리',
    summary: '닉스가 4쿼터 수비 집중력을 앞세워 홈에서 승리했습니다.',
    keyStats: [
      { label: '리바운드', value: '39 - 45', awayValue: 39, homeValue: 45 },
      { label: '야투 성공률', value: '46 - 49', awayValue: 46, homeValue: 49 },
      { label: '턴오버', value: '13 - 8', awayValue: 13, homeValue: 8 },
    ],
    playByPlay: ['4Q 0:32 닉스 자유투 성공', '2:10 히트 3점 실패'],
    lastUpdated: '어제',
  },
  {
    id: 6,
    league: 'NFL',
    status: 'UPCOMING',
    ...buildSeedSchedule(2, 9, 15),
    homeAbbr: 'DAL',
    awayAbbr: 'GB',
    homeRecord: '8-5',
    awayRecord: '8-5',
    homeTeam: 'Cowboys',
    awayTeam: 'Packers',
    homeScore: 0,
    awayScore: 0,
    period: '킥오프 대기',
    venue: 'AT&T Stadium',
    headline: '공격 밸런스가 승부처',
    summary: '패커스와 카우보이스가 와일드카드 경쟁에 중요한 맞대결을 앞두고 있습니다.',
    keyStats: [
      { label: '예상 승부', value: '접전 예상' },
      { label: '주목 매치업', value: 'Love vs Prescott' },
      { label: '핵심 변수', value: '턴오버 관리' },
    ],
    playByPlay: ['프리뷰만 제공 중입니다.'],
    lastUpdated: '내일 업데이트',
  },
  {
    id: 7,
    league: 'KBO',
    status: 'LIVE',
    ...buildSeedSchedule(0, 18, 30),
    homeAbbr: 'LGT',
    awayAbbr: 'KIA',
    homeRecord: '43-29',
    awayRecord: '45-27',
    homeTeam: 'LG Twins',
    awayTeam: 'KIA Tigers',
    homeScore: 5,
    awayScore: 6,
    period: '8회초 · 1사',
    venue: 'Jamsil Baseball Stadium',
    headline: '선두권 맞대결, KIA 1점 차 리드',
    summary: 'KIA가 장타력으로 앞서고 있지만 LG가 후반 추격을 이어가고 있습니다.',
    keyStats: [
      { label: '안타', value: '9 - 8', awayValue: 9, homeValue: 8 },
      { label: '홈런', value: '2 - 1', awayValue: 2, homeValue: 1 },
      { label: '볼넷', value: '4 - 3', awayValue: 4, homeValue: 3 },
    ],
    playByPlay: ['8회초 KIA 적시 2루타', '7회말 LG 희생플라이 득점', '5회초 KIA 투런 홈런'],
    lastUpdated: '방금 전',
  },
  {
    id: 8,
    league: 'KBO',
    status: 'FINAL',
    ...buildSeedSchedule(0, 18, 30),
    homeAbbr: 'SSG',
    awayAbbr: 'DSB',
    homeRecord: '38-34',
    awayRecord: '36-37',
    homeTeam: 'SSG Landers',
    awayTeam: 'Doosan Bears',
    homeScore: 3,
    awayScore: 7,
    period: '경기 종료',
    venue: 'Incheon SSG Landers Field',
    headline: '두산, 원정에서 7득점 완승',
    summary: '두산이 중반 대량 득점에 성공하며 SSG를 상대로 승리를 챙겼습니다.',
    keyStats: [
      { label: '안타', value: '11 - 6', awayValue: 11, homeValue: 6 },
      { label: '실책', value: '0 - 2', awayValue: 0, homeValue: 2 },
      { label: '잔루', value: '7 - 5', awayValue: 7, homeValue: 5 },
    ],
    playByPlay: ['7회초 두산 3점 추가', '4회초 두산 적시타 2개', '9회말 SSG 마지막 타자 삼진'],
    lastUpdated: '12분 전',
  },
  {
    id: 9,
    league: 'KBO',
    status: 'UPCOMING',
    ...buildSeedSchedule(1, 18, 30),
    homeAbbr: 'SAM',
    awayAbbr: 'LOT',
    homeRecord: '39-33',
    awayRecord: '34-38',
    homeTeam: 'Samsung Lions',
    awayTeam: 'Lotte Giants',
    homeScore: 0,
    awayScore: 0,
    period: '경기 시작 전',
    venue: 'Daegu Samsung Lions Park',
    headline: '영남 라이벌전 예정',
    summary: '삼성과 롯데가 중요한 중위권 맞대결을 앞두고 있습니다.',
    keyStats: [
      { label: '선발 매치업', value: '원태인 vs 반즈' },
      { label: '최근 10경기', value: '6승 4패 - 4승 6패' },
      { label: '관전 포인트', value: '초반 선취점' },
    ],
    playByPlay: ['라인업 발표 전입니다.'],
    lastUpdated: '일정 확정',
  },
  {
    id: 10,
    league: 'KBO',
    status: 'FINAL',
    ...buildSeedSchedule(-1, 18, 30),
    homeAbbr: 'HAN',
    awayAbbr: 'KIW',
    homeRecord: '37-35',
    awayRecord: '30-42',
    homeTeam: 'Hanwha Eagles',
    awayTeam: 'Kiwoom Heroes',
    homeScore: 4,
    awayScore: 2,
    period: '경기 종료',
    venue: 'Daejeon Hanwha Life Ballpark',
    headline: '한화, 불펜 지키며 2점 차 승리',
    summary: '한화가 후반 불펜 운영에 성공하며 키움을 제압했습니다.',
    keyStats: [
      { label: '안타', value: '8 - 5', awayValue: 8, homeValue: 5 },
      { label: '볼넷', value: '2 - 4', awayValue: 2, homeValue: 4 },
      { label: '도루', value: '1 - 0', awayValue: 1, homeValue: 0 },
    ],
    playByPlay: ['8회말 한화 결승타', '9회초 마무리 삼자범퇴'],
    lastUpdated: '어제',
  },
  {
    id: 11,
    league: 'KBO',
    status: 'UPCOMING',
    ...buildSeedSchedule(1, 18, 30),
    homeAbbr: 'KTW',
    awayAbbr: 'NCD',
    homeRecord: '35-36',
    awayRecord: '33-39',
    homeTeam: 'KT Wiz',
    awayTeam: 'NC Dinos',
    homeScore: 0,
    awayScore: 0,
    period: '경기 시작 전',
    venue: 'Suwon KT Wiz Park',
    headline: 'KT와 NC, 반등 노리는 맞대결',
    summary: '두 팀 모두 5할 복귀를 위해 중요한 경기입니다.',
    keyStats: [
      { label: '선발 매치업', value: '쿠에바스 vs 신민혁' },
      { label: '최근 10경기', value: '5승 5패 - 4승 6패' },
      { label: '핵심 변수', value: '불펜 소모도' },
    ],
    playByPlay: ['경기 프리뷰만 제공 중입니다.'],
    lastUpdated: '내일 업데이트',
  },
];
